// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Animal struct {
	Name    string `json:"name"`
	Species string `json:"species"`
}

type DeleteAnimal struct {
	Index int `json:"index"`
}

type NewAnimal struct {
	Name    string `json:"name"`
	Species string `json:"species"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user" gorm:"foreignKey:ID"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
